[package]
authors = ["Rust and WebAssembly Working Group"]
description = "A modular toolkit for Rust and WebAssembly"
edition = "2018"
license = "MIT/Apache-2.0"
name = "gloo"
readme = "README.md"
version = "0.3.0"
repository = "https://github.com/rustwasm/gloo"
homepage = "https://github.com/rustwasm/gloo"
categories = ["api-bindings", "wasm"]

[dependencies]
gloo-timers = { version = "0.2.0", path = "crates/timers" }
gloo-events = { version = "0.1.0", path = "crates/events" }
gloo-file = { version = "0.1.0", path = "crates/file" }
gloo-dialogs = { version = "0.1.0", path = "crates/dialogs" }
gloo-storage = { version = "0.1.0", path = "crates/storage" }
gloo-render = { version = "0.1.0", path = "crates/render" }
gloo-console = { version = "0.1.0", path = "crates/console" }

[features]
default = []
futures = ["gloo-timers/futures", "gloo-file/futures"]

[workspace]
members = [
    "crates/timers",
    "crates/events",
    "crates/file",
    "crates/dialogs",
    "crates/storage",
    "crates/console",
    "crates/utils",
]
