[package]
authors = ["Rust and WebAssembly Working Group"]
description = "A modular toolkit for Rust and WebAssembly"
edition = "2018"
license = "MIT/Apache-2.0"
name = "gloo"
readme = "README.md"
version = "0.2.1"
repository = "https://github.com/rustwasm/gloo"
homepage = "https://github.com/rustwasm/gloo"
categories = ["api-bindings", "wasm"]

[dependencies]
gloo-timers = { version = "0.2.0", path = "crates/timers" }
gloo-console-timer = { version = "0.1.0", path = "crates/console-timer" }
gloo-events = { version = "0.1.0", path = "crates/events" }
gloo-file = { version = "0.1.0", path = "crates/file" }
gloo-render = { version = "0.1.0", path = "crates/render" }

[features]
default = []
futures = ["gloo-timers/futures", "gloo-file/futures"]

[workspace]
