[package]
name = "gloo-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
    "Document",
    "History",
    "Location",
    "Window"
]
